import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const renderScript = "scripts/shirube/render-adoption-pack.mjs";
const checkScript = "scripts/shirube/check-adoption-pack.mjs";
const fixtures = path.join(root, "test/fixtures/shirube/adoption-pack-check");

function fixture(name: string): string {
  return path.join(fixtures, name);
}

function frameworkRef(): string {
  const head = execFileSync("git", ["rev-parse", "HEAD"], {
    cwd: root,
    encoding: "utf8",
  }).trim();
  return `watchout/ai-dev-framework@${head}`;
}

function run(script: string, args: string[]): { exitCode: number; json: any; stdout: string } {
  try {
    const stdout = execFileSync("node", [script, ...args], {
      cwd: root,
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    return { exitCode: 0, json: JSON.parse(stdout), stdout };
  } catch (error) {
    const err = error as { status?: number; stdout?: Buffer | string };
    const stdout = Buffer.isBuffer(err.stdout) ? err.stdout.toString("utf8") : err.stdout ?? "";
    return { exitCode: err.status ?? 1, json: JSON.parse(stdout), stdout };
  }
}

function render(out: string): void {
  const result = run(renderScript, [
    "--profile",
    "hotel-lite",
    "--target-repo",
    "watchout/example",
    "--product",
    "Example",
    "--source-control",
    "watchout/control#1",
    "--framework-ref",
    frameworkRef(),
    "--mode",
    "render",
    "--out",
    out,
    "--format",
    "json",
  ]);
  expect(result.exitCode).toBe(0);
}

function check(out: string, targetRepo = "watchout/example"): { exitCode: number; json: any; stdout: string } {
  return run(checkScript, [
    "--pack-root",
    out,
    "--target-repo",
    targetRepo,
    "--profile",
    "hotel-lite",
    "--format",
    "json",
  ]);
}

function withPack(fn: (out: string) => void): void {
  const out = mkdtempSync(path.join(tmpdir(), "shirube-adoption-pack-check-"));
  try {
    render(out);
    fn(out);
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
}

function blockerIds(result: { json: any }): string[] {
  return result.json.blockers.map((finding: { item_id: string }) => finding.item_id);
}

function expectShape(result: { json: any }): void {
  expect(result.json.schema).toBe("shirube-adoption-pack-check/v1");
  expect(["PASS", "PASS_WITH_WARN", "BLOCKED", "FAILURE"]).toContain(result.json.verdict);
  expect(result.json).toHaveProperty("would_block");
  expect(result.json).toHaveProperty("owner_must_not_merge");
  expect(result.json).toHaveProperty("target_repo");
  expect(result.json).toHaveProperty("profile");
  expect(result.json).toHaveProperty("inventory");
  expect(Array.isArray(result.json.blockers)).toBe(true);
  expect(Array.isArray(result.json.warnings)).toBe(true);
  expect(Array.isArray(result.json.required_next_actions)).toBe(true);
}

function replaceFile(file: string, pattern: string | RegExp, replacement: string): void {
  const text = readFileSync(file, "utf8");
  writeFileSync(file, text.replace(pattern, replacement));
}

function requiredFiles(): string[] {
  return readFileSync(fixture("required-files.txt"), "utf8")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

describe("Shirube adoption pack check", () => {
  it("passes a valid pack generated by render-adoption-pack", () => {
    withPack((out) => {
      const result = check(out);

      expect(result.exitCode).toBe(0);
      expectShape(result);
      expect(result.json.verdict).toBe("PASS");
      expect(result.json.would_block).toBe(false);
      expect(result.json.owner_must_not_merge).toBe(false);
      expect(result.json.blockers).toEqual([]);
      expect(result.json.inventory.files.required.map((file: { path: string; present: boolean }) => file.path)).toEqual(requiredFiles());
      for (const file of requiredFiles()) {
        expect(existsSync(path.join(out, file))).toBe(true);
      }
    });
  });

  it("blocks a missing execution context", () => {
    withPack((out) => {
      rmSync(path.join(out, ".shirube/execution-context.yaml"));
      const result = check(out);

      expect(result.exitCode).toBe(0);
      expectShape(result);
      expect(result.json.verdict).toBe("BLOCKED");
      expect(result.json.would_block).toBe(true);
      expect(blockerIds(result)).toContain("ADOPT-PACK-001");
      expect(blockerIds(result)).toContain("ADOPT-PACK-005");
    });
  });

  it("blocks a forbidden package.json file", () => {
    withPack((out) => {
      writeFileSync(path.join(out, "package.json"), "{}\n");
      const result = check(out);

      expect(result.exitCode).toBe(0);
      expect(result.json.verdict).toBe("BLOCKED");
      expect(blockerIds(result)).toContain("ADOPT-PACK-002");
      expect(blockerIds(result)).toContain("ADOPT-PACK-012");
    });
  });

  it("blocks copied scripts/shirube files", () => {
    withPack((out) => {
      mkdirSync(path.join(out, "scripts/shirube"), { recursive: true });
      writeFileSync(path.join(out, "scripts/shirube/copied.mjs"), "export {};\n");
      const result = check(out);

      expect(result.exitCode).toBe(0);
      expect(result.json.verdict).toBe("BLOCKED");
      expect(blockerIds(result)).toContain("ADOPT-PACK-002");
    });
  });

  it("blocks a source mirror that claims truth", () => {
    withPack((out) => {
      replaceFile(path.join(out, ".shirube/source-mirrors/control-issue.yaml"), "mirror_is_truth: false", "mirror_is_truth: true");
      const result = check(out);

      expect(result.exitCode).toBe(0);
      expect(result.json.verdict).toBe("BLOCKED");
      expect(blockerIds(result)).toContain("ADOPT-PACK-006");
    });
  });

  it("blocks an enforcement policy that is not report_only", () => {
    withPack((out) => {
      replaceFile(path.join(out, ".shirube/enforcement-policy.yaml"), "mode: report_only", "mode: owner_block");
      const result = check(out);

      expect(result.exitCode).toBe(0);
      expect(result.json.verdict).toBe("BLOCKED");
      expect(blockerIds(result)).toContain("ADOPT-PACK-007");
    });
  });

  it("blocks target repo mismatch", () => {
    withPack((out) => {
      const result = check(out, "watchout/other");

      expect(result.exitCode).toBe(0);
      expect(result.json.verdict).toBe("BLOCKED");
      expect(blockerIds(result)).toContain("ADOPT-PACK-004");
    });
  });

  it("blocks README missing LLM non-authority language", () => {
    withPack((out) => {
      replaceFile(path.join(out, "docs/shirube/README.md"), "LLM output is not authority.", "LLM output may inform review.");
      const result = check(out);

      expect(result.exitCode).toBe(0);
      expect(result.json.verdict).toBe("BLOCKED");
      expect(blockerIds(result)).toContain("ADOPT-PACK-010");
    });
  });

  it("blocks a full-control claim without readiness evidence", () => {
    withPack((out) => {
      replaceFile(path.join(out, ".shirube/adoption-intake.yaml"), "current_status: PARTIAL_SHIRUBE_PILOT", "current_status: FULL_CONTROL_READY");
      const result = check(out);

      expect(result.exitCode).toBe(0);
      expect(result.json.verdict).toBe("BLOCKED");
      expect(blockerIds(result)).toContain("ADOPT-PACK-011");
    });
  });

  it("returns FAILURE for malformed YAML", () => {
    withPack((out) => {
      writeFileSync(path.join(out, ".shirube/repo-spec.yaml"), "repo: [unterminated\n");
      const result = check(out);

      expect(result.exitCode).toBe(1);
      expectShape(result);
      expect(result.json.verdict).toBe("FAILURE");
      expect(result.json.would_block).toBe(true);
      expect(blockerIds(result)).toContain("ADOPT-PACK-003");
    });
  });
});
