/**
 * Retrofit templates - SSOT stub generators and report formatters
 */
import type {
  DetectedTech,
  ExpectedDoc,
  RetrofitReport,
} from "./retrofit-model.js";

/**
 * Generate SSOT stub content for a missing document
 */
export function generateSSOTStub(
  expected: ExpectedDoc,
  techStack: DetectedTech[],
  projectName: string,
): string {
  const date = new Date().toISOString().split("T")[0];
  const techList = techStack.map((t) => t.name).join(", ");

  switch (expected.ssoId) {
    case "SSOT-0":
      return generatePRDStub(projectName, techList, date);
    case "SSOT-1":
      return generateFeatureCatalogStub(projectName, date);
    case "SSOT-2":
      return generateUIStateStub(projectName, date);
    case "SSOT-3":
      return generateAPIContractStub(projectName, date);
    case "SSOT-4":
      return generateDataModelStub(projectName, date);
    case "SSOT-5":
      return generateCrossCuttingStub(projectName, date);
    case "STD-TECH":
      return generateTechStackDoc(techStack, projectName, date);
    default:
      return `# ${expected.name}\n\n> Generated by framework retrofit on ${date}\n> Project: ${projectName}\n\n---\n\n> **[要記入]** 既存の実装に基づいてこのドキュメントを記入してください。\n`;
  }
}

// ─────────────────────────────────────────────
// SSOT stub generators
// ─────────────────────────────────────────────

function generatePRDStub(
  projectName: string,
  techList: string,
  date: string,
): string {
  return `# SSOT-0: PRD - ${projectName}

> Generated by framework retrofit on ${date}
> Status: Draft - Review and complete all sections

---

## §1 Product Overview

| Item | Value |
|------|-------|
| Product Name | ${projectName} |
| Tech Stack | ${techList} |
| Status | Retrofitted from existing codebase |

## §2 Problem Statement

> **[要記入]** このプロダクトが解決する課題を記述してください。
> 例: 「中小企業の経費精算が紙ベースで月10時間かかっている」
> ヒント: 既存コードの README や LP があれば参照

## §3 Target Users

> **[要記入]** ターゲットユーザーを定義してください。
> 例: 「従業員50名以下の中小企業の経理担当者」

## §4 Solution Overview

> **[要記入]** 課題をどう解決するか記述してください。
> ヒント: 既存コードの主要機能から逆算

## §5 Functional Requirements

> **[要記入]** 既存コードから機能要件を抽出してください。
> Claude Code で自動抽出: "src/ のルート・コンポーネント・APIから機能要件を抽出して FR-001 形式でリストして"

## §6 Non-Functional Requirements

> **[要記入]** 性能・セキュリティ・スケーラビリティ要件を定義してください。
> 既存の設定ファイル（rate limit, cache, timeout 等）から抽出可能

## §7 Success Metrics

> **[要記入]** 測定可能な成功基準を定義してください。

## §8 Scope

> **[要記入]** スコープの内外を定義してください。

## §9 Milestones

> **[要記入]** プロジェクトのマイルストーンを定義してください。

## §10 Risks

> **[要記入]** プロジェクトリスクを特定してください。

## §11 Dependencies

> **[要記入]** 外部依存関係をリストしてください。
> ヒント: package.json / requirements.txt から自動抽出可能

## §12 Glossary

> **[要記入]** ドメイン固有の用語を定義してください。
`;
}

function generateFeatureCatalogStub(
  projectName: string,
  date: string,
): string {
  return `# SSOT-1: Feature Catalog - ${projectName}

> Generated by framework retrofit on ${date}
> Status: Draft - Extract features from existing codebase

---

## Feature List

| ID | Feature | Priority | Status | SSOT |
|----|---------|----------|--------|------|
| FEAT-001 | [要記入] | P0 | Existing | - |

> **[要記入]** 既存のルート・コンポーネント・APIエンドポイントを分析して機能カタログを構築してください。
> Claude Code で自動抽出: "src/ を分析して機能カタログを FEAT-XXX 形式で生成して"
`;
}

function generateUIStateStub(
  projectName: string,
  date: string,
): string {
  return `# SSOT-2: UI/State Transitions - ${projectName}

> Generated by framework retrofit on ${date}

---

## Screens

> **[要記入]** 既存の画面/ページをコードベースから抽出してください。
> Claude Code で自動抽出: "src/app/ のルートを分析して画面一覧を生成して"

## State Transitions

> **[要記入]** 既存のUI状態遷移ロジックをマッピングしてください。
`;
}

function generateAPIContractStub(
  projectName: string,
  date: string,
): string {
  return `# SSOT-3: API Contract - ${projectName}

> Generated by framework retrofit on ${date}

---

## API Endpoints

> **[要記入]** 既存のルートハンドラからAPIエンドポイントを抽出してください。
> Claude Code で自動抽出: "src/app/api/ を分析してAPIエンドポイント一覧を生成して"

| Method | Path | Description | Auth |
|--------|------|-------------|------|
| GET | /api/... | [要記入] | [要記入] |
`;
}

function generateDataModelStub(
  projectName: string,
  date: string,
): string {
  return `# SSOT-4: Data Model - ${projectName}

> Generated by framework retrofit on ${date}

---

## Tables / Collections

> **[要記入]** 既存のスキーマ/マイグレーションからデータモデルを抽出してください。
> Claude Code で自動抽出: "prisma/schema.prisma（または同等）を分析してテーブル一覧を生成して"

## Relationships

> **[要記入]** エンティティ間のリレーションシップを記述してください。
`;
}

function generateCrossCuttingStub(
  projectName: string,
  date: string,
): string {
  return `# SSOT-5: Cross-Cutting Concerns - ${projectName}

> Generated by framework retrofit on ${date}

---

## Authentication

> **[要記入]** 既存の認証実装を記述してください。
> ヒント: middleware, session, JWT, OAuth 等の実装を確認

## Error Handling

> **[要記入]** エラーハンドリングパターンを記述してください。
> ヒント: try-catch, error boundary, API error response の実装を確認

## Logging

> **[要記入]** ログ戦略を記述してください。
`;
}

function generateTechStackDoc(
  techStack: DetectedTech[],
  projectName: string,
  date: string,
): string {
  let content = `# Tech Stack - ${projectName}

> Auto-detected by framework retrofit on ${date}

---

## Detected Technologies

| Category | Technology | Version | Source |
|----------|-----------|---------|--------|
`;

  for (const tech of techStack) {
    content += `| ${tech.category} | ${tech.name} | ${tech.version ?? "-"} | ${tech.source} |\n`;
  }

  content += `
---

## Notes

> This document was auto-generated from package.json analysis.
> Review and add any technologies not detected automatically.
`;

  return content;
}

/**
 * Generate retrofit markdown report
 */
export function generateRetrofitMarkdown(
  report: RetrofitReport,
): string {
  const missingCount = report.gaps.filter((g) => g.status === "missing").length;
  const partialCount = report.gaps.filter((g) => g.status === "partial").length;
  const existsCount = report.gaps.filter((g) => g.status === "exists").length;

  let md = `# Retrofit Report - ${report.projectName}

> Scanned: ${report.scannedAt}

---

## Readiness Score

**${report.readiness.score}/${report.readiness.maxScore}**

| Check | Status | Points |
|-------|--------|--------|
`;

  for (const check of report.readiness.details) {
    const status = check.passed ? "PASS" : "FAIL";
    const detail = check.detail ? ` (${check.detail})` : "";
    md += `| ${check.name}${detail} | ${status} | ${check.passed ? check.points : 0}/${check.points} |\n`;
  }

  md += `
---

## Tech Stack

| Category | Technology | Version |
|----------|-----------|---------|
`;

  for (const tech of report.techStack) {
    md += `| ${tech.category} | ${tech.name} | ${tech.version ?? "-"} |\n`;
  }

  md += `
---

## File Statistics

| Metric | Value |
|--------|-------|
| Total Files | ${report.fileStats.totalFiles} |
| Total Lines | ${report.fileStats.totalLines} |
`;

  for (const [ext, count] of Object.entries(report.fileStats.byExtension)) {
    md += `| ${ext} files | ${count} |\n`;
  }

  md += `
---

## SSOT Gap Analysis

**${existsCount} exists / ${partialCount} partial / ${missingCount} missing**

| SSOT | Name | Status | Recommendation |
|------|------|--------|----------------|
`;

  for (const gap of report.gaps) {
    const statusIcon = gap.status === "exists" ? "EXISTS" : gap.status === "partial" ? "PARTIAL" : "MISSING";
    md += `| ${gap.ssoId} | ${gap.name} | ${statusIcon} | ${gap.recommendation} |\n`;
  }

  md += `
---

## Next Steps

1. Review and complete generated SSOT stubs
2. Run \`framework audit ssot <path>\` on each document
3. Use \`framework status\` to track progress
`;

  return md;
}
