/**
 * framework coherence - SSOT-Implementation consistency checker
 *
 * Usage:
 *   framework coherence              Check all SSOTs against implementation
 *   framework coherence --verbose    Show detailed comparison
 *   framework coherence --auto-fix   Auto-generate SSOT updates for divergences
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { type Command } from "commander";
import {
  runCoherence,
  createCoherenceTerminalIO,
} from "../lib/coherence-engine.js";
import {
  runModify,
  createModifyTerminalIO,
} from "../lib/modify-engine.js";
import { logger } from "../lib/logger.js";

export function registerCoherenceCommand(program: Command): void {
  program
    .command("coherence")
    .description(
      "Check SSOT-implementation consistency (no AI required)",
    )
    .option("--verbose", "Show detailed comparison results")
    .option("--auto-fix", "Auto-generate SSOT updates for detected divergences")
    .action(
      async (
        options: {
          verbose?: boolean;
          autoFix?: boolean;
        },
      ) => {
        const projectDir = process.cwd();
        const io = createCoherenceTerminalIO();

        try {
          const report = runCoherence({
            projectDir,
            verbose: options.verbose,
            io,
          });

          if (report.status === "diverged" && options.autoFix) {
            logger.info("");
            logger.info("Auto-fix: generating modification instructions from divergences...");

            // Generate a synthetic modification instruction from divergences
            const instruction = generateAutoFixInstruction(report);
            const autoFixPath = writeAutoFixInstruction(projectDir, instruction);

            const modifyIo = createModifyTerminalIO();
            const result = await runModify({
              projectDir,
              inputPath: autoFixPath,
              io: modifyIo,
            });

            if (result.errors.length > 0) {
              for (const err of result.errors) {
                logger.error(err);
              }
            }

            if (result.modifications.length > 0) {
              logger.success(
                `Auto-fix: ${result.modifications.length} modification(s) generated. Review with: framework modify --status`,
              );
            }
          } else if (report.status === "coherent") {
            // exit code 0 is default
          } else {
            // Diverged but no auto-fix
            process.exitCode = 0;
          }
        } catch (error) {
          if (error instanceof Error) {
            logger.error(error.message);
          }
          process.exit(1);
        }
      },
    );
}

function generateAutoFixInstruction(report: import("../lib/coherence-engine.js").CoherenceReport): string {
  const lines: string[] = [
    "# Auto-generated SSOT Update Instruction",
    "",
    `Generated by \`framework coherence --auto-fix\` at ${report.checkedAt}`,
    "",
    "## Detected Divergences",
    "",
  ];

  for (const result of report.results) {
    if (result.status !== "diverged") continue;

    lines.push(`### ${result.featureId} (${result.ssotPath})`);
    lines.push("");

    for (const d of result.divergences) {
      lines.push(`- **${d.section}** [${d.severity}] ${d.type}: ${d.detail}`);
    }
    lines.push("");
  }

  lines.push("## Required Updates");
  lines.push("");
  lines.push("Update the listed SSOT sections to match the current implementation code.");
  lines.push("For 'removed' items: either update the SSOT to remove the definition, or note that the implementation is missing.");
  lines.push("For 'changed' items: update the SSOT to reflect the current implementation.");

  return lines.join("\n");
}

function writeAutoFixInstruction(projectDir: string, content: string): string {
  const inboxDir = path.join(projectDir, "docs/inbox");
  if (!fs.existsSync(inboxDir)) {
    fs.mkdirSync(inboxDir, { recursive: true });
  }

  const fileName = `auto-fix-${new Date().toISOString().replace(/[:.]/g, "-")}.md`;
  const filePath = path.join(inboxDir, fileName);
  fs.writeFileSync(filePath, content, "utf-8");

  return path.join("docs/inbox", fileName);
}
